#!/usr/bin/env bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin                      
DAEMON=/usr/local/tengine/sbin/nginx
CONFIGFILE=/usr/local/tengine/conf/nginx.conf
PIDFILE=/var/run/nginx.pid
SCRIPTNAME=/etc/init.d/nginx
LOCKFILE=/var/lock/nginx.lock                       
set -e
[[ -x "$DAEMON" ]] || exit 0                                                  
start() {
    echo "Startting Nginx......"
    [[ -x $DAEMON ]] || exit 5
    [[ -f $CONFIGFILE ]] || exit 6
    $DAEMON -c $CONFIGFILE || echo -n "Nginx already running!"
    [[ $? -eq 0 ]] && touch $LOCKFILE
}                                                  
stop() {
    echo "Stopping Nginx......"
    MPID=`ps aux | grep nginx | awk '/master/{print $2}'`

    if [[ "${MPID}X" != "X" ]]; then
        kill -QUIT $MPID
        [[ $? -eq 0 ]] && rm -f $LOCKFILE
    else
        echo "Nginx server is not running!"
    fi
}                                                  
reload() {
    echo "Reloading Nginx......"
    MPID=`ps aux | grep nginx | awk '/master/{print $2}'`

    if [[ "${MPID}X" != "X" ]]; then
        kill -HUP $MPID
    else
        echo "Nginx can't reload!"
    fi
}                                             
case "$1" in
    start)
        start
        ;;                                                
    stop)
        stop
        ;;                                                
    reload)
        reload
        ;;                                                
    restart)
        stop
        sleep 1
        start
        ;;                                                  
    *)
        echo "Usage: $SCRIPTNAME {start|stop|reload|restart}"
        exit 3
        ;;
esac                                             
exit 0
